version: '3.8'

services:
  card-db:
    image: mysql:latest
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'cards'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MAX_ALLOWED_PACKET: 1073741824
    ports:
      - '3306:3306'
    volumes:
#      - "./scripts/:/docker-entrypoint-initdb.d"
      - db:/var/lib/mysql
    networks:
      - cards-network
#  logicea-cards 0.0.1-SNAPSHOT
volumes:
  db:
    driver: local
networks:
  cards-network:
    driver: bridge
